title: <p style="text-align:center">Ashraf <br> GHIYE</p>

logo: "https://github.com/ashrafghiye/ashrafghiye.github.io/blob/main/figures/ashrafghiye.jpg?raw=true"

author: Ashraf GHIYE

description: >
  <p style="text-align:center"><b>Ph.D. Student</b>
  <br><br>
  <a href="https://github.com/ashrafghiye" target="_blank">GitHub</a> - 
  <a href="https://www.linkedin.com/in/ashrafghiye/" target="_blank">LinkedIn</a> - 
  <a href="https://twitter.com/ashrafghiye" target="_blank">Twitter</a>
  <br> <br> 
  ashraf.ghiye [at] polytechnique [dot] edu
  <br> <br> <br> <br> <br> <br>
  <font size="1">Hosted on GitHub Pages &mdash; Theme by <a href="https://github.com/orderedlist" target="_blank">orderedlist</a></font>
  </p>

theme: jekyll-theme-minimal
include: index.md
# google_analytics: 
